### ISSUE TITLE
[Bug] ItemStackParser not working on 1.20.6

### ISSUE THREAD

**Issue by Xiao-MoMi** [Incendo/cloud-minecraft#69]
Tested on Paper version git-Paper-78 (MC: 1.20.6)
```[22:51:48 ERROR]: Error occurred while enabling Sparrow v1.5.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at net.momirealms.sparrow.libraries.cloud.bukkit.parser.ItemStackParser.<init>(ItemStackParser.java:118) ~[?:?]
        at net.momirealms.sparrow.libraries.cloud.bukkit.parser.ItemStackParser.itemStackParser(ItemStackParser.java:80) ~[?:?]
        at net.momirealms.sparrow.libraries.cloud.bukkit.BukkitCommandManager.<init>(BukkitCommandManager.java:131) ~[?:?]
        at net.momirealms.sparrow.libraries.cloud.paper.PaperCommandManager.<init>(PaperCommandManager.java:84) ~[?:?]
        at net.momirealms.sparrow.bukkit.command.SparrowBukkitCommandManager.<init>(SparrowBukkitCommandManager.java:114) ~[?:?]
        at net.momirealms.sparrow.bukkit.SparrowBukkitPlugin.setupCommandManager(SparrowBukkitPlugin.java:75) ~[?:?]
        at net.momirealms.sparrow.common.plugin.AbstractSparrowPlugin.enable(AbstractSparrowPlugin.java:36) ~[?:?]
        at net.momirealms.sparrow.bukkit.SparrowBukkitPlugin.enable(SparrowBukkitPlugin.java:52) ~[?:?]
        at net.momirealms.sparrow.bukkit.SparrowBukkitBootstrap.onEnable(SparrowBukkitBootstrap.java:144) ~[?:?]
        at Sparrow-Paper-1.5.0-f5484293.jar/net.momirealms.sparrow.paper.loader.PaperLoaderPlugin.onEnable(PaperLoaderPlugin.java:26) ~[Sparrow-Paper-1.5.0-f5484293.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-78]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-78]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:609) ~[paper-1.20.6.jar:git-Paper-78]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:558) ~[paper-1.20.6.jar:git-Paper-78]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[paper-1.20.6.jar:git-Paper-78]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[paper-1.20.6.jar:git-Paper-78]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:git-Paper-78]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-78]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-78]        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Couldn't find tag field on ItemInput
        at net.momirealms.sparrow.libraries.cloud.bukkit.internal.CraftBukkitReflection.firstNonNullOrThrow(CraftBukkitReflection.java:92) ~[?:?]
        at net.momirealms.sparrow.libraries.cloud.bukkit.parser.ItemStackParser$ModernParser.<clinit>(ItemStackParser.java:169) ~[?:?]
        ... 22 more
```
After decompiling the server and comparing the difference, I found that the field "tag" no longer exists, thus causing the error
[1.20.4]
![1 20 4](https://github.com/Incendo/cloud-minecraft/assets/70987828/397c5bdf-c496-48ca-ae81-dca6c4fd89aa)
[1.20.6]
![1 20 6](https://github.com/Incendo/cloud-minecraft/assets/70987828/19e6a18d-977f-4e62-8ab9-14c4c735eb05)

**Comment by jpenilla** [comment]
I can't reproduce this issue. tag is used as a fallback for <=1.20.4 Mojang mapped servers. The target field is still named `c` on spigot and modern Paper will remap the reflection.

**Comment by Xiao-MoMi** [comment]
Tested with spigot 1.20.6 and it's working as expected. Could it be problem that the field is "components" instead of
"tag" in 1.20.6 mojang mapped server.

**Comment by jpenilla** [comment]
No, that isn't a problem. My testing was on Paper as well. There must be something strange with your environment.

**Comment by Xiao-MoMi** [comment]
After creating a new plugin and shading the cloud into the jar, I found it's working well on 1.20.6 paper. The only difference is that I was using a JarInJarClassLoader as the screenshot below
![image](https://github.com/Incendo/cloud-minecraft/assets/70987828/1aa54392-fa50-415b-956f-6639287a138f)
Is there anyway to fix that? As it works fine both on 1.20.4 and 1.20.4 mojang mapping servers but not work on 1.20.6 paper

**Comment by jpenilla** [comment]
You should add the jar to the classpath using supported api like the PluginLoader or even spigots library downloader. Otherwise you need to apply reflection and bytecode remapping yourself. I can add the new name to the search list later, but you should really adjust how you load the inner jar on Paper.

**Comment by Xiao-MoMi** [comment]
Thanks! Have a good day
