### ISSUE TITLE
Error on paper 1.21

### ISSUE THREAD

**Issue by ChimpGamer** [Incendo/cloud-minecraft#80]
I get this error on Paper 1.21. I've cloud 2.0.0-rc.2 and cloud paper 2.0.0-beta.8
```[18:40:31] [Server thread/ERROR]: Error occurred while enabling UltimateMenus v1.0.0-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.lambda$new$0(MinecraftArgumentTypes.java:85) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[guava-32.1.2-jre.jar:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.getClassByKey(MinecraftArgumentTypes.java:98) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.bukkit.internal.MinecraftArgumentTypes.getClassByKey(MinecraftArgumentTypes.java:70) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.bukkit.internal.BukkitBrigadierMapper.registerUUID(BukkitBrigadierMapper.java:132) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.bukkit.internal.BukkitBrigadierMapper.registerBuiltInMappings(BukkitBrigadierMapper.java:82) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.paper.ModernPaperBrigadier.<init>(ModernPaperBrigadier.java:118) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.paper.LegacyPaperCommandManager.registerBrigadier(LegacyPaperCommandManager.java:174) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.paper.LegacyPaperCommandManager.registerBrigadier(LegacyPaperCommandManager.java:141) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/nl.chimpgamer.ultimatemenus.managers.CommandManager.initialize(CommandManager.kt:26) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/nl.chimpgamer.ultimatemenus.UltimateMenusPlugin.onEnable(UltimateMenusPlugin.kt:113) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-3-4514f41]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-3-4514f41]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-3-4514f41]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-3-4514f41]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-3-4514f41]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-3-4514f41]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-3-4514f41]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-3-4514f41]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-3-4514f41]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.resources.ResourceLocation.<init>(java.lang.String)
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.bukkit.internal.CraftBukkitReflection.needConstructor(CraftBukkitReflection.java:202) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:54) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	... 23 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.resources.ResourceLocation.<init>(java.lang.String)
	at java.base/java.lang.Class.getConstructor0(Class.java:3761) ~[?:?]
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.bukkit.internal.CraftBukkitReflection.needConstructor(CraftBukkitReflection.java:200) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	at UltimateMenus-v1.0.0-SNAPSHOT.jar/org.incendo.cloud.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:54) ~[UltimateMenus-v1.0.0-SNAPSHOT.jar:?]
	... 23 more
[18:40:31] [Server thread/INFO]: [UltimateMenus] Disabling UltimateMenus v1.0.0-SNAPSHOT
```

**Comment by jpenilla** [comment]
beta 8 only supports up to 1.20.6. use the snapshot or wait for the next beta
